# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp/precise64"
  config.vm.box_version = "1.1.0"

  # PRIVATE NETWORKING - Static IP, Dynamic IP"
  #config.vm.network "private_network", type:"dhcp"
  #config.vm.network "private_network", IP:"<ip-address>"

  # PUBLIC NETWORKING - Static & DHCP"
  #config.vm.network "public_network", type:"dhcp"
  #config.vm.network "public_network", bridge:'en1:Itecor Zurich 5Ghz'
  
  config.vm.network :forwarded_port, guest:80, host:8080
  
  # CHEF PROVISIONER #
  config.vm.provision "chef_solo" do |chef|
      chef.add_recipe "vagrant_la"
  end

end
