# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"


      # #Setup for web server#
      config.vm.define "web" do |web|
          web.vm.hostname = "web"
          web.vm.box = "apache"
          web.vm.network "private_network", type: "dhcp"
          web.vm.network "forwarded_port", guest: 80, host: 8081
          web.vm.provision "puppet" do |puppet|
              puppet.manifests_path = "manifests/apache2/"
              puppet.manifest_file = "default.pp"
          end
      end           

      # Setup for MySQL DB Server #
      # ACTUALLY DOESN'T WORK #
      # config.vm.define "db" do |db|
      #     db.vm.hostname = "db"
      #     db.vm.box = "mysql"
      #     db.vm.network "private_network", type: "dhcp"
      #     db.vm.provision "puppet" do |puppet|
      #         puppet.manifests_path = "manifests/mysql/"
      #         puppet.manifest_file = "default.pp"
      #     end
      # end

end
