# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "docker"
  config.vm.network "private_network", type:"dhcp"
  config.vm.provision :shell, path:"docker_ic.sh"

  
end
